language: ruby
rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.0
 - 2.2.0
 - 2.3.0
 - 2.4.0
 - 2.5.0
env:
 - "MPFR="
 - "MPFR=no-mpfr"
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgmp3-dev libmpfr-dev
 - gem install bundler -v 1.17.2
